In [1]:
test = "Hello world"
print(test)

Hello world


In [2]:
import numpy as np

In [3]:
one_dimensional_arr = np.array([10,12])
print(one_dimensional_arr)

[10 12]


In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.arange(3)

In [7]:
print(b)

[0 1 2]


In [12]:
# array, interval (3)
c=np.arange(1,20,3)

In [13]:
print(c)

[ 1  4  7 10 13 16 19]


In [9]:
print(c)

[ 1  4  7 10 13 16 19]


In [11]:
# Five evenly spaced array(1-100, divide in 5)
lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [17]:
# dtype assigns data type
lin_spaced_arr_int = np.linspace(0,100,5, dtype=int)
lin_spaced_arr_int

array([  0,  25,  50,  75, 100])

In [18]:
c_int = np.arange(1,20,3, dtype=int)
c_int

array([ 1,  4,  7, 10, 13, 16, 19])

In [19]:
b_float = np.arange(3,dtype=float)
b_float

array([0., 1., 2.])

In [20]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) #prints the data type of the array

['Welcome to Math for ML!']
<U23


In [25]:
# Make an array with '1's
ones_arr = np.ones(3, dtype=int)
print(ones_arr)

[1 1 1]


In [26]:
# Make an array with '0's
zeros_arr=np.zeros(3, dtype=int)
print(zeros_arr)

[0 0 0]


In [28]:
# Make an empty array
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [29]:
# Return a new array of shape 3 with random numbers between 0 and 1
rand_arr = np.random.rand(3)
print(rand_arr)

[0.36453581 0.66361297 0.01689471]


In [33]:
# Create a 2 dimensional array
two_dimen_arr = np.array([[1,2,3],[4,5,6]])
print(two_dimen_arr)

[[1 2 3]
 [4 5 6]]


In [34]:
# Make 1 dimenstional array
one_dim_arr = np.array([1,2,3,4,5,6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
    one_dim_arr,
    (2,3)
)

# Print the new 2-D array with two rows ant three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [35]:
# Dimension of the 2-D array
multi_dim_arr.ndim

2

In [36]:
# shape of the 2-D array 
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [37]:
# Size of the array
# Returns total number of elements
multi_dim_arr.size

6

In [38]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [39]:
vector = np.array([1,2])
vector * 1.6

array([1.6, 3.2])

In [40]:
a = np.array([1,2,3,4,5])
print(a[2])

3


In [41]:
print(a[0])

1


In [42]:
# Indexing of 2-D array
two_dim = np.array(([1,2,3],[4,5,6],[7,8,9]))

# Select element number 8 from the 2-D array using indices i, j and two sets of brackets
print(two_dim[2][1])

# Select element number 8 from 2-D array. This time using i and j indexes in a single set of brackets sepaarated by comma
print(two_dim[2,1])

8
8


In [43]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [44]:
sliced_arr_2 = a[:3]
print(sliced_arr_2)

[1 2 3]


In [47]:
sliced_arr_3 = a[2:]
print(sliced_arr_3)

sliced_arr_interval = a[::2]
print(sliced_arr_interval)
sliced_arr_1_two = two_dim[0:2]
sliced_arr_1_two

[3 4 5]
[1 3 5]


array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
sliced_arr_1_two = two_dim[0:1]

In [49]:
sliced_arr_1_two

array([[1, 2, 3]])

In [50]:
sliced_arr_2_two = two_dim[1:]
sliced_arr_2_two

array([[4, 5, 6],
       [7, 8, 9]])

In [52]:
# This is very important!
# This example uses slice notation to get every row, and then pulls the second column.
# Notice how this example combines slice notation with the use of multiple indexes
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


In [53]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [55]:
# Stacks array in vertical direction
vert_stack = np.vstack((a1,a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [57]:
# Stacks arrays in horizontal direction
hor_stack = np.hstack((a1,a2))
print(hor_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [58]:
# Split the horizontally stacked array into 2 separate arrays of equal size
horz_split_two = np.hsplit(hor_stack,2)
print(horz_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
horz_split_four = np.hsplit(hor_stack, 4)
print(horz_split_four)

# Split the horizontally stacked array after the first column
horz_split_first = np.hsplit(hor_stack, [1])
print(horz_split_first)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1],
       [2]]), array([[1],
       [2]]), array([[3],
       [4]]), array([[3],
       [4]])]
[array([[1],
       [2]]), array([[1, 3, 3],
       [2, 4, 4]])]


In [59]:
# Split the vertically stacked array into 2 separate arrays of equal size
vert_split_two = np.vsplit(vert_stack,2)
print(vert_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
vert_split_four = np.vsplit(vert_stack,4)
print(vert_split_four)

# Split the horizontally stacked array after the first and third row
vert_split_first_third = np.vsplit(vert_stack, [1,3])
print(vert_split_first_third)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1, 1]]), array([[2, 2]]), array([[3, 3]]), array([[4, 4]])]
[array([[1, 1]]), array([[2, 2],
       [3, 3]]), array([[4, 4]])]


In [60]:
# One thing to remember. Arrays are stacked in vertical direction
# array [1,1] is row 1 and row 2
# array ([1,1], [2,2]) is row 1 = 1,2 / row 2 = 1,2
# Just think of vectors.